modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"
issueTrackerURL="https://example.invalid/"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="water_spring"
version="${file.jarVersion}"
displayName="Water Spring"
description="Infinite water!"
authors="3TUSK"

[[dependencies.water_spring]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"